version: "3.8"

services:
  app:
    container_name: go-template
    build: .
    image: go-template
    volumes:
      - .:/app
    depends_on:
      - database
    env_file:
      - .env
    ports:
      - 4000:4000

  database:
    container_name: postgres-db-1
    volumes:
      - /db/postgres/data
    image: postgres:alpine3.14
    restart: always
    ports:
      - 5432:5432
    env_file:
      - database.env